In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\raksh\OneDrive\Documents\Data-Science-AIML-Portfolio\Projects\Portfolio_projects\01 - E-Commerce_Business_Analytics\data\raw\customer_master.csv')
df.head()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34

In [6]:
df.shape

(25000, 11)

In [7]:
df['customer_name'].nunique()

21631

In [8]:
df.isnull().sum()

customer_id                  0
customer_name                0
customer_age                 0
gender                       0
customer_segment             0
customer_city                0
customer_state               0
customer_country             0
region                       0
customer_postal_code         0
customer_acquisition_cost    0
dtype: int64

In [19]:
df[df.duplicated(subset='customer_name', keep=False)].head()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
7,CUST-000008,Trevor Brown,40,Male,Consumer,Hillport,Illinois,USA,Central,63970,66.68
13,CUST-000014,Kimberly Nguyen,72,Female,Consumer,Lisafurt,Pennsylvania,USA,East,48344,72.75

In [10]:
df.groupby('customer_name')['customer_id'].nunique().value_counts()

customer_id
1     19265
2      1790
3       369
4       111
5        51
6        18
7        11
9         6
8         3
10        2
11        2
12        1
17        1
15        1
Name: count, dtype: int64

In [20]:
# Confirm how many unique customer IDs you actually have
df['customer_name'].nunique()

21631

In [13]:
# See the distribution
df['customer_id'].value_counts().describe()

count    25000.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
Name: count, dtype: float64

In [25]:
df[df['customer_name'] == 'Daniel Smith'].value_counts()

customer_id  customer_name  customer_age  gender  customer_segment  customer_city        customer_state  customer_country  region  customer_postal_code  customer_acquisition_cost
CUST-000003  Daniel Smith   47            Male    Consumer          Seanview             North Rhine     Germany           West    13900                 31.53                        1
CUST-000926  Daniel Smith   41            Female  Premium           New Kristineborough  Georgia         USA               South   75633                 27.59                        1
CUST-014976  Daniel Smith   54            Female  Premium           Brandifort           England         UK                North   98149                 38.39                        1
CUST-016798  Daniel Smith   60            Male    Premium           South Abigailville   Wales           UK                West    22993                 29.08                        1
CUST-017247  Daniel Smith   25            Male    Premium           South Jefferybury    North Carolina  USA               South   9975                  43.37                        1
Name: count, dtype: int64