In [1]:
import pandas as pd
import numpy as np

In [2]:
#Reading the data from CSV format.
df = pd.read_csv(r'C:\Users\raksh\OneDrive\Documents\Data-Science-AIML-Portfolio\Machine Learning\Datasets\Housing.csv')

In [3]:
#Display the data in DataFrame format.
df.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [4]:
#To check for null values
df.isnull().sum()

price       0
lotsize     0
bedrooms    0
bathrms     0
stories     0
driveway    0
recroom     0
fullbase    0
gashw       0
airco       0
garagepl    0
prefarea    0
dtype: int64

In [5]:
#To check for the datatypes, memory usage, and columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     546 non-null    float64
 1   lotsize   546 non-null    int64
 2   bedrooms  546 non-null    int64
 3   bathrms   546 non-null    int64
 4   stories   546 non-null    int64
 5   driveway  546 non-null    str
 6   recroom   546 non-null    str
 7   fullbase  546 non-null    str
 8   gashw     546 non-null    str
 9   airco     546 non-null    str
 10  garagepl  546 non-null    int64
 11  prefarea  546 non-null    str
dtypes: float64(1), int64(5), str(6)
memory usage: 51.3 KB

**3 thumb rule**
- No Null values
- No Outliers
- Data should be in numrical format, We need to convert categorical values into numerical columns.

In [6]:
#We are applying get dummies on our dataframe so that our categorical values were converted to numerical value by dropping the first instances(drop_first=True)


dum_df = pd.get_dummies(df, drop_first=True)


#we can do labelEncoder as well.

In [7]:
dum_df.head()

,price,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,42000.0,5850,3,1,2,1,True,False,True,False,False,False
1,38500.0,4000,2,1,1,0,True,False,False,False,False,False
2,49500.0,3060,3,1,1,0,True,False,False,False,False,False
3,60500.0,6650,3,1,2,0,True,True,False,False,False,False
4,61000.0,6360,2,1,1,0,True,False,False,False,False,False

- We can see that the Categorial values are converted into Boolean values. 

- In the below code we can see that the categorical values are converted to Boolean datatypes.

In [8]:
dum_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         546 non-null    float64
 1   lotsize       546 non-null    int64
 2   bedrooms      546 non-null    int64
 3   bathrms       546 non-null    int64
 4   stories       546 non-null    int64
 5   garagepl      546 non-null    int64
 6   driveway_yes  546 non-null    bool
 7   recroom_yes   546 non-null    bool
 8   fullbase_yes  546 non-null    bool
 9   gashw_yes     546 non-null    bool
 10  airco_yes     546 non-null    bool
 11  prefarea_yes  546 non-null    bool
dtypes: bool(6), float64(1), int64(5)
memory usage: 28.9 KB

In [9]:
#We get the list of columns of the dataframes
dum_df.columns

Index(['price', 'lotsize', 'bedrooms', 'bathrms', 'stories', 'garagepl',
       'driveway_yes', 'recroom_yes', 'fullbase_yes', 'gashw_yes', 'airco_yes',
       'prefarea_yes'],
      dtype='str')

- We need to seperate our input columns and the output columns for further Model Training.

- Always assign 'y' to our predicted column and 'X' to our independent varaibles/input variables.

In [10]:
#We are creating two variables to store our Target variable as 'y' and input variables as 'X'
y = dum_df.iloc[:,0]
X = dum_df.iloc[:,1:12]

In [11]:
#For quick check/Verify on variables are correctly setup.
y.head()
X.head()

,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,5850,3,1,2,1,True,False,True,False,False,False
1,4000,2,1,1,0,True,False,False,False,False,False
2,3060,3,1,1,0,True,False,False,False,False,False
3,6650,3,1,2,0,True,True,False,False,False,False
4,6360,2,1,1,0,True,False,False,False,False,False

- Now our dataset is ready, we need to split our data into train and test subsets.

- In this process we split our dataset into 80:20 percent where 80% data will be used for traing the model and after training we will use the 20% unseen data to validate if the model is producing the desired outcome.

- We split the data into 80 and 20 in those we will have 80: y & X and also in the 20: y & X.

- We train the model on 80% data where we fit our linear Regression algorithm which have a equation: y = mx + c.

- After that machine learns patterns through equation on training data and now we use our 20% unseen data to test the model,

- Where it predicts the predicted values in yp1,yp2,..yp20, in those data you will also have Actual Target values like ya1,ya2,...ya20.

- Now we will compare the The actual values with the predicted values. based on the no of correct / incorrect you will have the accuracy like 90%--so on.


- If we don't split the data into train and test and using any test data from the dataset itself, then the model will remember the patterns of the data and which leads to higher accuracy which considered as overfitting.

- Ex: if mobile cost is 200, and if the model predicts 201 which is not a coorect prediction

In [12]:
#We use Sklearn library to split our data into train and test.
from sklearn.model_selection import train_test_split

Why do we split the data? Through general example

- Imagine you're preparing for an examination.
- You study 80 questions from a textbook.
- Then you take a test containing the exact same 80 questions.
- You score 95%.
- Does that prove you can solve new questions?
- Not necessarily. You might have memorized the answers.
- Now imagine taking an examination with 20 new questions you've never seen before.

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

```py
Variable	Contains	    Purpose
X_train	  Training features	Inputs used to train the model
y_train	  Training targets	Correct answers used during training
X_test	  Test features	    Unseen inputs given to the trained model
y_test	  Test targets	    Actual answers used to evaluate predictions
```

In [14]:
print(X_train.shape)
print(X_test.shape)
print(X.shape)
print("-"*20)
print(y_train.shape)
print(y_test.shape)
print(y.shape)

(436, 11)
(110, 11)
(546, 11)
--------------------
(436,)
(110,)
(546,)

In [15]:
#We are importing our Linear Regression Model.
from sklearn.linear_model import LinearRegression

In [16]:
#We have defined our Regression Model
regressor = LinearRegression()

In [17]:
#We are running our model on training data
regressor.fit(X_train, y_train)

LinearRegression()

Linear Regression Equation: Y = Mx + C

In [18]:
#We will look into the M = Co-efficient our alogorithm.
print(regressor.coef_)

[3.65398978e+00 9.55865044e+02 1.35822404e+04 7.20464908e+03
 4.61164795e+03 6.94001236e+03 4.55674435e+03 6.37702327e+03
 1.51289605e+04 1.26746163e+04 7.81519389e+03]

In [19]:
#We will look for C = intercept of our algorithm.
print(regressor.intercept_)

-2513.002578839063

In [20]:
#We will predict our outcomes.
y_pred = regressor.predict(X_test) #This will be an array of list.
print(y_pred)

[ 67965.39055778  66913.33565631 109975.8073368   61158.44011902
  56327.64653371  58151.61312818  55973.55336425  54269.43150634
  98832.10215503  48611.08929595  78646.1834425   95179.76473042
  53624.82795496  63566.1906301   98074.03694856 108523.5594545
  77166.88378398  40353.07238342  89400.67770365  54178.60229425
  33271.36551707  49729.63973815  76571.45417133  52756.67973564
  73626.89153725  39262.70314866  86422.39003048  42754.50627868
 100859.04475166  59969.65556986  51312.01343866  77074.93596408
  74028.29195949  92757.17729035  61334.59457096  53295.81704549
  34443.79799155  67190.0825052   70946.78849416 103443.75010887
  43595.7350214  110558.61242543  40752.2375375   54707.91028046
  77237.66559779  58881.07946019  56348.36629339  55261.35070339
  55350.48922308  98048.1937209   39351.60451815  77407.80537511
  77395.34745099  79022.75207675  67877.89857558  85184.69811495
 105217.63452376  73435.3578292   61261.28264669 110967.98686514
  52625.13610341  86648.38919897  75822.83051178  70185.88114271
  30818.72727947  59076.12744221  44329.7682007   66567.53192816
  59457.28590773  67927.87647317 113854.60837219  90089.88541593
  67448.13511163  48623.20619726 102487.88506442  32761.16956568
  82046.30047821  50097.93779108  41995.20781517  84441.25853393
  52898.3742449   62320.89401253  76332.3968167   68658.53312756
  54653.29845385  43568.58339361  52636.30575922  65915.62354599
  67650.65494253  31147.58636005  58611.85164914  62576.71896904
 101475.92620877  43939.81007257  49350.22541518  87147.63061004
  49354.00415412  46248.11283746  80885.81388111  53050.3615368
  64649.62511924  38776.02907563  44054.50846102  46112.14230479
  51438.20317452 100021.45763574  51654.94851486  73331.33923839
  66003.39035135  31293.74595143]

- Now we have to find errors using evaluation metrics like MAE, MSE, & R2 Score.

**Regression Loss Errors:**

**Mean Absolute Error [MAE]**
- It measures the average absolute difference between predicted and actual values, It shows how accurate a model's prediction are.

- MAE should be low to confirm good prediction after that other parameters to be considered.

**Mean Squared Error [MSE]**
- It measures the average of the squared differences between predicted and actual values. the squaring is the key difference from MAE -- It penalizes large errors disproportionately.

**R2_Score**
- Coefficient of Determination measures the proportion of variance in the target variable explained by the model. It gives you accuracy.


- R2 answers "Is the model actually capturing the patterns, or just noise?".
- MAE/RMSE answers "How big are the typical errors in real world units?".

In [22]:
#Importing mean_squared_error, mean_absolute_error, r2_Score from sklearn.metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#printing Mean Squared Error (MSE)
print("MSE -->",np.sqrt(mean_squared_error(y_test, y_pred)))

#Printing Mean Absolute Error (MAE)
print("MAE -->",mean_absolute_error(y_test, y_pred))

#Printing R2 Score
print("R2 Score -->",r2_score(y_test, y_pred))

MSE --> 16016.397426383444
MAE --> 11463.135922494639
R2 Score --> 0.6160238969106218

- Our model is predicted very bad.