### ```Polynomial Regression```

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\raksh\OneDrive\Documents\Data-Science-AIML-Portfolio\Machine Learning\Datasets\Concrete_Data.csv')

In [3]:
#Displaying the data
df.head()

   Cement  Blast  Fly  Water  Superplasticizer  Coarse   Fine  Age  Strength
0   540.0    0.0  0.0  162.0               2.5  1040.0  676.0   28     79.99
1   540.0    0.0  0.0  162.0               2.5  1055.0  676.0   28     61.89
2   332.5  142.5  0.0  228.0               0.0   932.0  594.0  270     40.27
3   332.5  142.5  0.0  228.0               0.0   932.0  594.0  365     41.05
4   198.6  132.4  0.0  192.0               0.0   978.4  825.5  360     44.30

- Need to check 3 mandatory step to ready for analysis.

1. No null
2. All features are in numerical, if not convert to numeric.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Cement            1030 non-null   float64
 1   Blast             1030 non-null   float64
 2   Fly               1030 non-null   float64
 3   Water             1030 non-null   float64
 4   Superplasticizer  1030 non-null   float64
 5   Coarse            1030 non-null   float64
 6   Fine              1030 non-null   float64
 7   Age               1030 non-null   int64
 8   Strength          1030 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 72.6 KB

In [5]:
df.isnull().sum()

Cement              0
Blast               0
Fly                 0
Water               0
Superplasticizer    0
Coarse              0
Fine                0
Age                 0
Strength            0
dtype: int64

##### ```Exploratory Data Analysis [EDA]```

In [6]:
#!pip install ydata-profiling

In [7]:
from ydata_profiling import ProfileReport

c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\raksh\AppData\Local\Temp\ipykernel_25356\4135506147.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [8]:
profile = ProfileReport(df, title='Concrete_Data_Profiling_Report')

In [9]:
profile.to_file("Concrete_data_report.html")

100%|██████████| 9/9 [00:00<00:00, 2235.90it/s]<?, ?it/s, Describe variable: Strength]
Summarize dataset: 100%|██████████| 99/99 [00:06<00:00, 15.81it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.46s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.48it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 76.84it/s]

In [10]:
import matplotlib.pyplot as plt

In [11]:
df.columns

Index(['Cement', 'Blast', 'Fly', 'Water', 'Superplasticizer', 'Coarse', 'Fine',
       'Age', 'Strength'],
      dtype='object')

In [12]:
X = df.iloc[:,:8]
y = df.iloc[:,8]

In [13]:
y

0       79.99
1       61.89
2       40.27
3       41.05
4       44.30
        ...
1025    44.28
1026    31.18
1027    23.70
1028    32.77
1029    32.40
Name: Strength, Length: 1030, dtype: float64

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [15]:
#We set our degree for 2 for the polynomial variable
poly = PolynomialFeatures(degree=2)

In [16]:
#We need to fit our polynomial variable to be fit on X training data.
X_poly = poly.fit_transform(X)

In [17]:
X_poly

array([[1.0000000e+00, 5.4000000e+02, 0.0000000e+00, ..., 4.5697600e+05,
        1.8928000e+04, 7.8400000e+02],
       [1.0000000e+00, 5.4000000e+02, 0.0000000e+00, ..., 4.5697600e+05,
        1.8928000e+04, 7.8400000e+02],
       [1.0000000e+00, 3.3250000e+02, 1.4250000e+02, ..., 3.5283600e+05,
        1.6038000e+05, 7.2900000e+04],
       ...,
       [1.0000000e+00, 1.4850000e+02, 1.3940000e+02, ..., 6.0840000e+05,
        2.1840000e+04, 7.8400000e+02],
       [1.0000000e+00, 1.5910000e+02, 1.8670000e+02, ..., 6.2236321e+05,
        2.2089200e+04, 7.8400000e+02],
       [1.0000000e+00, 2.6090000e+02, 1.0050000e+02, ..., 5.7988225e+05,
        2.1322000e+04, 7.8400000e+02]], shape=(1030, 45))

In [18]:
original_features = X.columns
original_features

Index(['Cement', 'Blast', 'Fly', 'Water', 'Superplasticizer', 'Coarse', 'Fine',
       'Age'],
      dtype='object')

In [19]:
features_names = poly.get_feature_names_out(input_features=original_features)

In [20]:
#Display the results
print("Original features: ", original_features)
print("Generated Features names: ", features_names)
print("Transformed data shape: ", X_poly.shape)

Original features:  Index(['Cement', 'Blast', 'Fly', 'Water', 'Superplasticizer', 'Coarse', 'Fine',
       'Age'],
      dtype='object')
Generated Features names:  ['1' 'Cement' 'Blast' 'Fly' 'Water' 'Superplasticizer' 'Coarse' 'Fine'
 'Age' 'Cement^2' 'Cement Blast' 'Cement Fly' 'Cement Water'
 'Cement Superplasticizer' 'Cement Coarse' 'Cement Fine' 'Cement Age'
 'Blast^2' 'Blast Fly' 'Blast Water' 'Blast Superplasticizer'
 'Blast Coarse' 'Blast Fine' 'Blast Age' 'Fly^2' 'Fly Water'
 'Fly Superplasticizer' 'Fly Coarse' 'Fly Fine' 'Fly Age' 'Water^2'
 'Water Superplasticizer' 'Water Coarse' 'Water Fine' 'Water Age'
 'Superplasticizer^2' 'Superplasticizer Coarse' 'Superplasticizer Fine'
 'Superplasticizer Age' 'Coarse^2' 'Coarse Fine' 'Coarse Age' 'Fine^2'
 'Fine Age' 'Age^2']
Transformed data shape:  (1030, 45)

In [21]:
#View as a pandas dataframe
df_poly = pd.DataFrame(X_poly, columns=features_names)

In [22]:
df_poly.head()

,1,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Cement^2,...,Superplasticizer^2,Superplasticizer Coarse,Superplasticizer Fine,Superplasticizer Age,Coarse^2,Coarse Fine,Coarse Age,Fine^2,Fine Age,Age^2
0,1.0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28.0,291600.00,...,6.25,2600.0,1690.0,70.0,1081600.00,703040.0,29120.0,456976.00,18928.0,784.0
1,1.0,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28.0,291600.00,...,6.25,2637.5,1690.0,70.0,1113025.00,713180.0,29540.0,456976.00,18928.0,784.0
2,1.0,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270.0,110556.25,...,0.00,0.0,0.0,0.0,868624.00,553608.0,251640.0,352836.00,160380.0,72900.0
3,1.0,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365.0,110556.25,...,0.00,0.0,0.0,0.0,868624.00,553608.0,340180.0,352836.00,216810.0,133225.0
4,1.0,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360.0,39441.96,...,0.00,0.0,0.0,0.0,957266.56,807669.2,352224.0,681450.25,297180.0,129600.0

- In reality we cannot ignore any feature as it has its own specific ability until and unless if it is triveal. For Example if you see the Superplasticizer where the values are decreased from 2.5 --> 0 it doesn't mean it doesn't have an coreleation, it acts to specific season and other features where it supports.

- now will split the data into train and test split

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X_poly,y, test_size=0.2, random_state=42)

In [25]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [26]:
y_pred = regressor.predict(X_test)

In [27]:
y_pred

array([38.32051572, 49.51480123, 63.19972931, 47.95378188, 16.12908377,
       43.39425269, 29.47721838, 58.5734343 , 25.80900575, 46.3237506 ,
       36.15004489,  8.96543959, 43.84816749, 43.30577896, 28.73816612,
       32.55630044, 32.15202739, 22.25414428, 37.34998935, 29.02613991,
       35.43208955, 49.04427447, 43.05669635, 15.53692126, 30.36681015,
       29.99871182, 10.73013848, 44.79239078, 55.62677304, 21.438927  ,
       39.54061096, 33.15758329, 43.97418029, 63.20659602, 24.79873174,
       31.26607408, 26.75404138, 41.58089166, 13.76772678, 44.79050324,
       19.90703084,  7.57849511, 38.00708217, 46.33510481, 14.57597492,
       66.50370076, 43.79405246, 31.97440979, 22.37154999, 12.97751705,
       45.22875194, 43.30443232, 27.15867048, 23.47443359, 45.15390917,
       47.38726146, 20.75402821, 14.75281173, 34.05985295, 19.37722861,
       41.38081893, 17.47345138, 42.47223738, 51.75187667, 24.22808129,
       17.12020217, 37.59343421, 16.47370325, 28.82721688, 22.30560887,
       12.31830386, 20.36385586, 10.30762447, 36.10164571, 28.07828806,
       11.58602241, 36.34300668, 58.0856611 , 61.81542061, 13.71869087,
       51.97985875, 38.80967628, 39.07094789, 33.36421275, 44.88825908,
       47.95378188, 34.39769647, 36.87735962, 23.57966252, 18.32883106,
       29.47227578, 78.43903415, 18.67051949, 48.42589604, 40.00811125,
       51.22144036, 26.60598883, 28.90409538, 26.13620361, 36.12334247,
       30.33633863, 41.43906022, 53.73043998, 28.97440879, 78.06686901,
       12.94929052, 59.75262297, 32.92623758, 31.10040365, 57.59782936,
       52.203447  , 43.22568535, 25.73346447, 43.86239822, 45.06860033,
       66.12677804, 22.89866669, 35.6879917 , 53.80346237, 39.93240616,
       28.89947622, 28.59632872, 43.19658185, 34.14013485, 15.09442023,
       37.79606047, 49.82689464, 45.64621556, 41.18704281, 38.3359131 ,
       14.60295005, 28.40030291, 12.18594283, 66.05661517,  5.45472922,
       55.37105558, 24.71059959, 44.94727042, 24.56385816, 33.84885397,
       34.09157634, 34.7813055 , 24.07225616, 32.16669992, 47.45414818,
       36.75755689, 28.37109876, 16.76610332, 12.43360092, 19.44654505,
       33.58631491, 18.47727882, 41.48448115, 28.44544166, 51.60046283,
       43.76144424, 31.68010663, 75.95450301, 49.51480123, 46.04118144,
       16.75124308, 45.58584818, 28.52262303, 46.29897085, 44.00156977,
       65.22155964, 46.44378036, 22.44921982, 48.90520863, 25.84018833,
       38.65334811, 18.5861826 , 16.07894113, 34.99399847, 30.64432773,
       15.01011258, 22.95549118, 44.76909944, 46.53592873, 48.65711825,
       37.86631517, 23.17129596, 57.4650023 , 49.22323475, 40.61058539,
       48.98854339, 22.97249403, 31.11737882, 42.38759491, 17.8104815 ,
       39.79716661, 59.27119527, 47.75884769, 41.85360046, 24.38533231,
       28.38661338, 50.16546466, 18.31121888, 28.32714114, 14.59614435,
       38.96651529, 66.12677804, 12.33874423, 49.16169795, 61.57032975,
       39.69548688])

In [29]:
#Coefficients
print("Co-efficients: ",regressor.coef_)

#Intercept
print("Intercept: ",regressor.intercept_)

Co-efficients:  [ 9.89420932e-10  2.55014345e+00  1.96012335e+00  1.17756824e+00
  1.44648273e+01  3.62818607e+01  2.80957436e+00  3.81424993e+00
 -7.15678473e-02 -3.24398839e-04 -3.71455265e-04 -4.55371420e-05
 -4.69996897e-03 -1.20379967e-02 -6.34932228e-04 -8.92141057e-04
  3.02326141e-04 -1.30226408e-04  4.40542638e-04 -3.94753684e-03
 -1.27137097e-02 -5.63934067e-04 -5.72222581e-04  5.77399588e-04
  4.14713117e-04 -4.02336880e-03 -1.94371143e-02 -2.40789815e-04
 -1.86130200e-04  9.85252544e-04 -8.55594307e-03 -3.70434547e-02
 -5.01152782e-03 -5.97904480e-03 -9.47742043e-05 -4.86366758e-02
 -1.19319911e-02 -1.50056183e-02  1.51614809e-03 -4.05659301e-04
 -1.04570931e-03  6.56810878e-06 -8.55788681e-04  3.19048436e-04
 -6.23004712e-04]
Intercept:  -4695.99206559755

In [28]:
#Importing mean_squared_error, mean_absolute_error, r2_Score from sklearn.metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#printing Mean Squared Error (MSE)
print("MSE -->",np.sqrt(mean_squared_error(y_test, y_pred)))

#Printing Mean Absolute Error (MAE)
print("MAE -->",mean_absolute_error(y_test, y_pred))

#Printing R2 Score
print("R2 Score -->",r2_score(y_test, y_pred))

MSE --> 7.455364369393239
MAE --> 5.969585860201223
R2 Score --> 0.7842939778602838

- try degree 3, 4 to find what is the exact fit 

- Pizza data set try.