## ```LRE Regression```

### ```Example (House Price Prediction)```

- Assume we want to predict House Price using these features:

    1. Size of house (sqft)
    2. Number of rooms
    3. Distance from city center.
    4. Wall color (red/blue) --> Not important
    5. Owners' Lucky Number --> Not important

- Some features are usefull, while some are useless in nature.
-------------------------------------------------------------------

#### **1. Lasso Regression (L1)**

**What is Lasso does?**
- Lasso tries to remove useless features completely.

**Example Outcome:**
- After Training the model:

```
Feature         Coefficient
Size                45
Rooms               30
Distance           -20
Wall Color           0
Lucky Number         0
```

**Explanation in Simple Words:**
- Lasso decided that **wall color** and **lucky number** do not matter.
- Their weights became **zero**.
- The model ignores them completely.

**When this is usefull**
- When you have many features.
- When you want the model to automatically choose important features ones.


- Sometimes it leads to overfitting due to some features are removed by coefficients to zero that leads to some coorelation between them.

-------------------------------------------------------------------
#### **2. Ridge regression (L2)**

**What Ridge does?**
- Ridge tries to **reduces the effect of features**, but it does not remove any.

**Example Outcomes:**

```
Features        Coefficients
Size               30
Rooms              20
Distance          -15
Wall color          2
Lucky Nymber        1
```

**Explanation in simple words**
- All features are still used.
- Even useless features get small weights.
- The model is more stable and less overfitted.

**When this is useful**
- When all features have some importance.
- When features are related to each other.
-------------------------------------------------------------------

#### **3. Elastic Net (L1 + L2)**

**What does Elastic net does?**
- Elastic net removes useless features and shrinks the important ones.

**Example Outcome:**

```
features            Coefficients
Size                   35
Rooms                  25
Distance              -18
Wall Color              0
Lucky Number            0
```

**Explanation in Simple words**
- Useless features are removed.
- Important features are controlled.
- Model is balanced and stable.
-------------------------------------------------------------------

#### **4. Key Difference using the SAME example**

```
Model                       What Happenend
Lasso        --------   Removed wall color and lucky number
Ridge        --------   Kept all features but reduced impact
Elastic Net  --------   Removes useless ones and shrinks others.
```
-------------------------------------------------------------------

#### **5. Short Interview-friendly Explantion**
- **Lasso** removes unnecessary features by setting coefficients to zero.
- **Ridge** keeps all features but reduces their influence.
- **Elastic Net** combines both by removing useless features and stabilizing important ones.

-------------------------------------------------------------------

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Reading the data from CSV format.
df = pd.read_csv(r'C:\Users\raksh\OneDrive\Documents\Data-Science-AIML-Portfolio\Machine Learning\Datasets\Housing.csv')

In [3]:
df.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [4]:
#To check for null values
df.isnull().sum()

price       0
lotsize     0
bedrooms    0
bathrms     0
stories     0
driveway    0
recroom     0
fullbase    0
gashw       0
airco       0
garagepl    0
prefarea    0
dtype: int64

In [5]:
#To check for the datatypes, memory usage, and columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     546 non-null    float64
 1   lotsize   546 non-null    int64
 2   bedrooms  546 non-null    int64
 3   bathrms   546 non-null    int64
 4   stories   546 non-null    int64
 5   driveway  546 non-null    object
 6   recroom   546 non-null    object
 7   fullbase  546 non-null    object
 8   gashw     546 non-null    object
 9   airco     546 non-null    object
 10  garagepl  546 non-null    int64
 11  prefarea  546 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 51.3+ KB

In [6]:
#We are applying get dummies on our dataframe so that our categorical values were converted to numerical value by dropping the first instances(drop_first=True)
dum_df = pd.get_dummies(df, drop_first=True)

In [7]:
dum_df.head()

,price,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,42000.0,5850,3,1,2,1,True,False,True,False,False,False
1,38500.0,4000,2,1,1,0,True,False,False,False,False,False
2,49500.0,3060,3,1,1,0,True,False,False,False,False,False
3,60500.0,6650,3,1,2,0,True,True,False,False,False,False
4,61000.0,6360,2,1,1,0,True,False,False,False,False,False

In [8]:
#To understand the columns after dummies where categorical converted to boolean
dum_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         546 non-null    float64
 1   lotsize       546 non-null    int64
 2   bedrooms      546 non-null    int64
 3   bathrms       546 non-null    int64
 4   stories       546 non-null    int64
 5   garagepl      546 non-null    int64
 6   driveway_yes  546 non-null    bool
 7   recroom_yes   546 non-null    bool
 8   fullbase_yes  546 non-null    bool
 9   gashw_yes     546 non-null    bool
 10  airco_yes     546 non-null    bool
 11  prefarea_yes  546 non-null    bool
dtypes: bool(6), float64(1), int64(5)
memory usage: 28.9 KB

In [9]:
#We get the list of columns of the dataframes
dum_df.columns

Index(['price', 'lotsize', 'bedrooms', 'bathrms', 'stories', 'garagepl',
       'driveway_yes', 'recroom_yes', 'fullbase_yes', 'gashw_yes', 'airco_yes',
       'prefarea_yes'],
      dtype='object')

In [10]:
#We are creating two variables to store our Target variable as 'y' and input variables as 'X'
y = dum_df.iloc[:,0]
X = dum_df.iloc[:,1:12]

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=42)

#### ```Lasso regression (L1)```

In [12]:
from sklearn.linear_model import Lasso

In [42]:
clf = Lasso(alpha=3, selection='random') #We are taking alpha as 3 as we can take from (0 - inf)

- Alpha value is controlling the intercept values. It make values closer to our alpha.

In [43]:
clf.fit(X_train, y_train)

Lasso(alpha=3, selection='random')

In [44]:
print(clf.coef_)

[3.65684369e+00 9.53803236e+02 1.35767173e+04 7.20530713e+03
 4.61195199e+03 6.91582066e+03 4.54633017e+03 6.37329123e+03
 1.50431150e+04 1.26590095e+04 7.80079002e+03]

In [45]:
print(clf.intercept_)

-2479.7438279086346

In [46]:
y_pred = clf.predict(X_test)

In [47]:
#Importing mean_squared_error, mean_absolute_error, r2_Score from sklearn.metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#printing Mean Squared Error (MSE)
print("MSE -->",np.sqrt(mean_squared_error(y_test, y_pred)))

#Printing Mean Absolute Error (MAE)
print("MAE -->",mean_absolute_error(y_test, y_pred))

#Printing R2 Score
print("R2 Score -->",r2_score(y_test, y_pred))

MSE --> 16014.832855664416
MAE --> 11459.85175220399
R2 Score --> 0.6160989110862856

- We can conclude that Lasso Regression is not a good fit for our model.

#### ```Ridge Regression (L2)```

In [48]:
from sklearn.linear_model import Ridge

In [55]:
rdg = Ridge(alpha=3)

In [56]:
rdg.fit(X_train, y_train)

Ridge(alpha=3)

In [57]:
print(rdg.coef_)

[3.70189298e+00 1.06669630e+03 1.32598539e+04 7.24997740e+03
 4.68095729e+03 6.58170837e+03 4.56482891e+03 6.32535327e+03
 1.26089289e+04 1.21485622e+04 7.49412201e+03]

In [58]:
print(rdg.intercept_)

-2130.892579264473

In [59]:
y_pred = rdg.predict(X_test)

In [60]:
#Importing mean_squared_error, mean_absolute_error, r2_Score from sklearn.metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#printing Mean Squared Error (MSE)
print("MSE -->",np.sqrt(mean_squared_error(y_test, y_pred)))

#Printing Mean Absolute Error (MAE)
print("MAE -->",mean_absolute_error(y_test, y_pred))

#Printing R2 Score
print("R2 Score -->",r2_score(y_test, y_pred))

MSE --> 15979.449476321348
MAE --> 11364.651259589373
R2 Score --> 0.6177934291571721

- We can also consider that Ridge is alos not a good fit for our model.

#### ```Elastic Net Regression (L1+L2)```

In [61]:
from sklearn.linear_model import ElasticNet

In [62]:
enr = ElasticNet(alpha=3, l1_ratio=0.6)

In [63]:
enr.fit(X_train, y_train)

ElasticNet(alpha=3, l1_ratio=0.6)

In [64]:
print(enr.coef_)

[   5.84696305 2038.62521972 2941.79909808 3858.8649586  2427.94694416
  910.28581576 1224.4869092  1514.73089454  431.76052844 2394.48133202
 1314.33680383]

In [65]:
print(enr.intercept_)

17196.93583487913

In [66]:
y_pred = enr.predict(X_test)

In [67]:
#Importing mean_squared_error, mean_absolute_error, r2_Score from sklearn.metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#printing Mean Squared Error (MSE)
print("MSE -->",np.sqrt(mean_squared_error(y_test, y_pred)))

#Printing Mean Absolute Error (MAE)
print("MAE -->",mean_absolute_error(y_test, y_pred))

#Printing R2 Score
print("R2 Score -->",r2_score(y_test, y_pred))

MSE --> 19720.507235595465
MAE --> 13961.255901142214
R2 Score --> 0.4178824592605521

- We can consider this model doesn't fit good with housing data.