### ```LRE (Medical Insurance Data)```

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\raksh\OneDrive\Documents\Data-Science-AIML-Portfolio\Machine Learning\Datasets\insurance.csv')

In [3]:
#Quick Inspection
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
#To check for null values
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
#To check for the datatypes, memory usage, and columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [6]:
dum_df = pd.get_dummies(df, drop_first=True)
dum_df.head()

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False

In [7]:
#To understand the columns after dummies where categorical converted to boolean
dum_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               1338 non-null   int64
 1   bmi               1338 non-null   float64
 2   children          1338 non-null   int64
 3   charges           1338 non-null   float64
 4   sex_male          1338 non-null   bool
 5   smoker_yes        1338 non-null   bool
 6   region_northwest  1338 non-null   bool
 7   region_southeast  1338 non-null   bool
 8   region_southwest  1338 non-null   bool
dtypes: bool(5), float64(2), int64(2)
memory usage: 48.5 KB

In [8]:
#We get the list of columns of the dataframes
dum_df.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype='object')

In [9]:
#Divide the data into Independent and target variable
X = dum_df.drop('charges', axis=1)
y = dum_df['charges']

In [10]:
#Importing train test split function from sklearn.
from sklearn.model_selection import train_test_split

In [ ]:
#splitting data into train set and test set.
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=2026)

#### ```Linear Regression```

In [12]:
#Importing our Linear Regression Algorithm.
from sklearn.linear_model import LinearRegression

In [13]:
#Creating an object for our Linear model.
regressor = LinearRegression()

In [14]:
#We are using our object to train our algorithm on our splitted training data.
regressor.fit(X_train, y_train)

LinearRegression()

In [15]:
#Understanding the coefficients
print("Co-efficients: ", regressor.coef_)

Co-efficients:  [  257.320049     348.21764832   517.58472652   -91.40147662
 23630.42271185   -30.02874427  -677.77537491  -902.72167731]

In [16]:
#Checking for Intercept of our data
print("Intercept: ", regressor.intercept_)

Intercept:  -12527.481347394154

In [17]:
#Now we are predicting on test data
y_pred = regressor.predict(X_test)

In [18]:
#Importing mean_squared_error, mean_absolute_error, r2_Score from sklearn.metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#printing Mean Squared Error (MSE)
print("MSE -->",np.sqrt(mean_squared_error(y_test, y_pred)))

#Printing Mean Absolute Error (MAE)
print("MAE -->",mean_absolute_error(y_test, y_pred))

#Printing R2 Score
print("R2 Score -->",r2_score(y_test, y_pred))

MSE --> 6106.778332556117
MAE --> 4218.30525962794
R2 Score --> 0.7637143742908048

#### ```Polynomial Regression```

In [19]:
#importing our polynomial model
from sklearn.preprocessing import PolynomialFeatures

In [21]:
#We are creating a polyinomial features object with degree = 2.
poly = PolynomialFeatures(degree=2)

In [22]:
#We are transform on X first and then split our data.
X_poly = poly.fit_transform(X)

In [ ]:
#Split train test library.
from sklearn.model_selection import train_test_split

In [23]:
#Train test split
X_train, X_test, y_train, y_test = train_test_split(X_poly,y, test_size=0.20, random_state=2026)

In [36]:
#We are checking how degree = 2 works with original and generated features.
original_features = X.columns
original_features

Index(['age', 'bmi', 'children', 'sex_male', 'smoker_yes', 'region_northwest',
       'region_southeast', 'region_southwest'],
      dtype='object')

In [37]:
#Generated features for degree = 2
generated_features = poly.get_feature_names_out(input_features=original_features)
generated_features

array(['1', 'age', 'bmi', 'children', 'sex_male', 'smoker_yes',
       'region_northwest', 'region_southeast', 'region_southwest',
       'age^2', 'age bmi', 'age children', 'age sex_male',
       'age smoker_yes', 'age region_northwest', 'age region_southeast',
       'age region_southwest', 'bmi^2', 'bmi children', 'bmi sex_male',
       'bmi smoker_yes', 'bmi region_northwest', 'bmi region_southeast',
       'bmi region_southwest', 'children^2', 'children sex_male',
       'children smoker_yes', 'children region_northwest',
       'children region_southeast', 'children region_southwest',
       'sex_male^2', 'sex_male smoker_yes', 'sex_male region_northwest',
       'sex_male region_southeast', 'sex_male region_southwest',
       'smoker_yes^2', 'smoker_yes region_northwest',
       'smoker_yes region_southeast', 'smoker_yes region_southwest',
       'region_northwest^2', 'region_northwest region_southeast',
       'region_northwest region_southwest', 'region_southeast^2',
       'region_southeast region_southwest', 'region_southwest^2'],
      dtype=object)

In [39]:
X_poly.shape

(1338, 45)

In [24]:
#We are creating an Linear model object for our Polynomial algorithm.
regressor = LinearRegression()

In [25]:
#Training the data
regressor.fit(X_train, y_train)

LinearRegression()

In [26]:
#Understanding the coefficients
print("Co-efficients: ", regressor.coef_)

Co-efficients:  [ 2.30233504e-08 -7.16954586e+01  5.03635304e+02  8.84566141e+02
 -9.02184728e+02 -1.02913153e+04  4.44771956e+02  1.13619306e+03
  1.28150416e+02  3.42996689e+00  8.29069512e-01  3.29141103e-01
  2.08268291e+01  1.53402565e+01 -2.94948716e+00  4.68843432e+01
  5.14693101e+01 -7.69640659e+00  1.55506206e+01  3.34386088e+01
  1.45259634e+03 -3.91630321e+01 -1.35235719e+02 -9.29527647e+01
 -3.98223929e+01 -3.70999566e+02 -5.00154593e+02  5.34340527e+01
 -4.53316541e+02 -5.51453458e+02 -9.02184728e+02  1.76991049e+02
 -3.61976368e+02  8.32127610e+01 -1.90949752e+02 -1.02913153e+04
  2.74749745e+02 -1.24249622e+03  5.09719634e+02  4.44771956e+02
  0.00000000e+00  0.00000000e+00  1.13619306e+03  0.00000000e+00
  1.28150416e+02]

In [34]:
#Checking for Intercept of our data
print("Intercept: ", regressor.intercept_)

Intercept:  -4243.017624472643

In [35]:
#Now we are predicting on test data
y_pred = regressor.predict(X_test)

In [40]:
#Importing mean_squared_error, mean_absolute_error, r2_Score from sklearn.metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#printing Mean Squared Error (MSE)
print("MSE -->",np.sqrt(mean_squared_error(y_test, y_pred)))

#Printing Mean Absolute Error (MAE)
print("MAE -->",mean_absolute_error(y_test, y_pred))

#Printing R2 Score
print("R2 Score -->",r2_score(y_test, y_pred))

MSE --> 4678.0987071432855
MAE --> 2846.5290127898916
R2 Score --> 0.8613398222409084

#### ```Lasso Regression (L1)```

In [45]:
#From sklearn we are importing our Lasso Regression
from sklearn.linear_model import Lasso

In [46]:
#splitting data into train set and test set.
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=2026)

In [60]:
#Creating a lasso object
clf = Lasso(alpha=4)

In [61]:
#Training the data on lasso algorithm.
clf.fit(X_train, y_train)

Lasso(alpha=4)

In [62]:
print(clf.coef_)

[  257.3341934    347.30874387   514.63283231   -74.16152646
 23603.9981391      0.          -626.59525624  -854.07636656]

In [63]:
print(clf.intercept_)

-12533.644373053714

In [64]:
y_pred = clf.predict(X_test)

In [65]:
#Importing mean_squared_error, mean_absolute_error, r2_Score from sklearn.metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#printing Mean Squared Error (MSE)
print("MSE -->",np.sqrt(mean_squared_error(y_test, y_pred)))

#Printing Mean Absolute Error (MAE)
print("MAE -->",mean_absolute_error(y_test, y_pred))

#Printing R2 Score
print("R2 Score -->",r2_score(y_test, y_pred))

MSE --> 6108.776712959696
MAE --> 4218.3385242892255
R2 Score --> 0.76355970490614

#### ```Lasso with Polynomial Regression (Trail & error Method)```

In [66]:
#Split train test library.
from sklearn.model_selection import train_test_split

In [67]:
#Train test split
X_train, X_test, y_train, y_test = train_test_split(X_poly,y, test_size=0.20, random_state=2026)

In [68]:
#We are creating an Linear model object for our Polynomial algorithm.
regressor = LinearRegression()

In [69]:
#Training the data
regressor.fit(X_train, y_train)

LinearRegression()

In [70]:
#Now we are predicting on test data
y_pred = regressor.predict(X_test)

In [71]:
#Importing mean_squared_error, mean_absolute_error, r2_Score from sklearn.metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#printing Mean Squared Error (MSE)
print("MSE -->",np.sqrt(mean_squared_error(y_test, y_pred)))

#Printing Mean Absolute Error (MAE)
print("MAE -->",mean_absolute_error(y_test, y_pred))

#Printing R2 Score
print("R2 Score -->",r2_score(y_test, y_pred))

MSE --> 4678.0987071432855
MAE --> 2846.5290127898916
R2 Score --> 0.8613398222409084

#### ```Ridge Regression (L2)```

In [53]:
#Importing our Ridge algorithm
from sklearn.linear_model import Ridge

In [72]:
#splitting data into train set and test set.
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=2026)

In [73]:
#Creating an object for Ridge
clf = Ridge(alpha=3)

In [74]:
#training the data with Ridge
clf.fit(X_train, y_train)

Ridge(alpha=3)

In [75]:
#Understanding the Coefficients
print(clf.coef_)

[  257.01018306   346.72134403   516.65916509   -68.3880364
 23224.81072635   -30.08819171  -630.08625376  -895.86443762]

In [76]:
#Checing the intercept of the data points.
print(clf.intercept_)

-12411.359754346697

In [77]:
#predicting on test data
y_pred = clf.predict(X_test)

In [78]:
#Importing mean_squared_error, mean_absolute_error, r2_Score from sklearn.metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#printing Mean Squared Error (MSE)
print("MSE -->",np.sqrt(mean_squared_error(y_test, y_pred)))

#Printing Mean Absolute Error (MAE)
print("MAE -->",mean_absolute_error(y_test, y_pred))

#Printing R2 Score
print("R2 Score -->",r2_score(y_test, y_pred))

MSE --> 6121.020967245798
MAE --> 4249.425608465824
R2 Score --> 0.7626109269118436

#### ```Elastic Net Regression (L1 + L2)```

In [79]:
from sklearn.linear_model import ElasticNet

In [80]:
#splitting data into train set and test set.
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=2026)

In [87]:
clf = ElasticNet(alpha=0, l1_ratio=0.6)

In [88]:
clf.fit(X_train, y_train)

c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
c:\Users\raksh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.945e+10, tolerance: 1.538e+07
Linear regression models with a zero l1 penalization strength are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

ElasticNet(alpha=0, l1_ratio=0.6)

In [89]:
print(clf.coef_)

[  257.320049     348.21764832   517.58472652   -91.40147662
 23630.42271185   -30.02874427  -677.77537491  -902.72167731]

In [90]:
print(clf.intercept_)

-12527.481347394212

In [91]:
y_pred = clf.predict(X_test)

In [92]:
#Importing mean_squared_error, mean_absolute_error, r2_Score from sklearn.metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#printing Mean Squared Error (MSE)
print("MSE -->",np.sqrt(mean_squared_error(y_test, y_pred)))

#Printing Mean Absolute Error (MAE)
print("MAE -->",mean_absolute_error(y_test, y_pred))

#Printing R2 Score
print("R2 Score -->",r2_score(y_test, y_pred))

MSE --> 6106.778332556117
MAE --> 4218.305259627941
R2 Score --> 0.7637143742908048

In [ ]:
#Trail code for quick check.
for row in range(6):
    for col in range(7):
        if ((row == 0 and col % 3 != 0) or
           (row == 1 and col % 3 == 0) or
           (row - col == 2) or
           (row + col == 8)):
            print("*", end=" ")
        else:
            print(" ", end=" ")
    print()

  * *   * *
*     *     *
*           *
  *       *
    *   *
      *