### ```Pandas Exercise SF Salaries```

- The Sanfransico Salaries dataset is pulledd from Kaggle. 
- The link to download: https://www.kaggle.com/datasets/kaggle/sf-salaries

In [1]:
import pandas as pd

In [2]:
# Q1. Read salaries data into a dataframe.
sal = pd.read_csv('Salaries.csv')

C:\Users\raksh\AppData\Local\Temp\ipykernel_23792\2796333812.py:2: DtypeWarning: Columns (0: BasePay, 1: OvertimePay, 2: OtherPay, 3: Benefits, 4: Status) have mixed types. Specify dtype option on import or set low_memory=False.
  sal = pd.read_csv('Salaries.csv')

In [3]:
# Q2. Display the dataframe
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [4]:
# Q3. Use the info() method to find out how many entries are there.
sal.info()

<class 'pandas.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  str
 2   JobTitle          148654 non-null  str
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  str
 12  Status            38119 non-null   str
dtypes: float64(3), int64(2), object(4), str(4)
memory usage: 14.7+ MB

In [5]:
# Q4. We are converting important string column to numeric due to potential analysis.
sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors='coerce')
sal['OvertimePay'] = pd.to_numeric(sal['OvertimePay'], errors='coerce')
sal['OtherPay'] = pd.to_numeric(sal['OtherPay'], errors='coerce')
sal['Benefits'] = pd.to_numeric(sal['Benefits'], errors='coerce')

In [6]:
#Q5. What is the average Base Pay?
sal['BasePay'].mean()

np.float64(66325.44884048769)

In [7]:
#Q6. What is the highest amount of OvertimePay in the dataset?
sal['OvertimePay'].max()

np.float64(245131.88)

Q7. What is the job title of JOSEPH DRISCOLL? Note: Use all caps, otherwise you may get answer that doesn't match as there is lower case Joshep driscoll.

In [8]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

In [9]:
# Q8. How much does JOSEPH DRISCOLL make include benefits.

sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [10]:
# Q9. What is the name of highest paid person (including benefits)?
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

In [11]:
#Advanced method
sal.loc[sal['TotalPayBenefits'].idxmax()]

Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                  167411.18
OvertimePay                                                    0.0
OtherPay                                                 400184.25
Benefits                                                       NaN
TotalPay                                                 567595.43
TotalPayBenefits                                         567595.43
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object

In [12]:
# Q10. What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?

sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,PT

In [13]:
#Advanced method
sal.iloc[sal['TotalPayBenefits'].argmin()]

Id                                      148654
EmployeeName                         Joe Lopez
JobTitle            Counselor, Log Cabin Ranch
BasePay                                    0.0
OvertimePay                                0.0
OtherPay                               -618.13
Benefits                                   0.0
TotalPay                               -618.13
TotalPayBenefits                       -618.13
Year                                      2014
Notes                                      NaN
Agency                           San Francisco
Status                                      PT
Name: 148653, dtype: object

In [14]:
# Q11. What was the average(mean) basepay of all employees per year? [2011-2014]
sal.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [15]:
# Q12. How many unique job titles are there?
sal['JobTitle'].nunique()

2159

In [16]:
# Q13. What are the top 5 most common jobs?

sal['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [17]:
# Q14. How many job titles were represented by only one person in 2013? E.g. Job titles with only one occurrance in 2013.

sum(sal[sal['Year'] == 2013]['JobTitle'].value_counts() == 1)

202

In [45]:
# How many people have the word chief in their job titles?

sal[sal['JobTitle'].str.contains('.*Chief', case=False)]['Id'].count()

np.int64(627)

In [52]:
# Is there a correlation between length of the job title string and salary?

sal['Title_len'] = sal['JobTitle'].apply(len)

In [56]:
sal[['Title_len','TotalPayBenefits']].corr()

                  Title_len  TotalPayBenefits
Title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000