### ```End-To-End Data Analytics Project: Titanic Data Analysis```

**Project Workflow:**
```py
        Business Problem
            |
        Dataset Understanding
            |
        Data Quality Assessment
            |
        Data Cleaning & Preparation
            |
        Exploratory Data Analysis (EDA)
            |
        Visualization
            |
        Insights / Findings
            |
        Recommendations
            |
        Conclusions
```

##### ```1. Business Problem:```

"Analyze Titanic Passengers data to identify factors affecting survival".

- What factors influenced passengers to survive.
- Ask Question Why, How, what, which


**Analytics:**
- Identify Survival patterns
- Understand high-risk passenger groups.
- Find relationships between demographics and survival.
- Generate insights using historical passenger data.

In [57]:
#Importing necessary libraries for analysis.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### ```2. Dataset Understanding```
- Reading the data from the source.
- Head() to validate the data in dataframe format by looking at the data.


Checks:
- Understand the data
- Columns check (dependent/Independent columns)
- How many records (rows & Columns)
- Describe & Info to understand statistically manner.
- Finding Target variable (How it is dependent with other columns)

In [58]:
# Reading the CSV File.
df = pd.read_csv('Titanic.csv')  #We have the csv in project folder so we can directly use the name or else we need to give whole path.

In [59]:
#Displaying the CSV data using Head() for 5 rows to validate in DataFrame format.
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [60]:
# Checking what columns are present
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

**Columns:**
- PassengerID: Unique Passenger Number
- Survived: 0-Not Survived, 1-Survived
- Pclass: Passenger Class
- Name: Name of the passenger
- Sex: Male, Female
- Age: Passenger Age at the time of travel
- Sib Sp: Sibilings / Spouse present on Titanic
- Parch: Parents / Children present on Titanic
- Ticket: Unique passenger Ticket
- Fare: Price for the travel
- Cabin: Compartment class of booking.
- Embarked: Boarding Point

In [61]:
#Shape of the data
df.shape

(891, 12)

#### ```3. Data Quality Assessment```

- Missing Values Checks
- Duplicates
- Wrong Data types
- Invalid values
- Outliers

In [62]:
#Checking the Information.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

**Observations:**
```py
- We can see that a total of 891 rows and 12 Columns exist in the dataset
- 11 feature inputs and 1 Target Variable (Survived)
- Each column has its own datatypes.
- We can see the Age, Cabin column has more missing values than Embarked column.
- Ticket & Name Columns are potentially lower priority.
```


**Proceedings:**
```py
- If there are any mismatch in the column datatypes we can typecast to desired datatypes.
- From the missing rows, we can validate them and proceed with either Imputation or dropping the rows based on null percentage.
- We can cross check the Cabin column and based on that we can decide whether we need to drop or untouch.

Generally if a column has 60% Null values we can proceed with Imputation of Mean, median, or mode based on columns, and if columns are 20% we can proceed with dropping them.

- We need to check the Age distribution and based on that we need to decide
- Is the distribution is normal or skewed?

Note: Age will not be normal as they are passenger of different groups like children, adults, elders. If distribution is Skewed use "Median".
```

In [65]:
#Statistical Summary
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [66]:
#Checking for Null values
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [68]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [69]:
#Finding the duplicate rows
df[df.duplicated()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

**Observation:**
```py
- Age: Need to check distribution based on that if normal we can go for Mean or else skewed we can go with Median.
- Cabin: Need to understand the column more if it gives any feature benefits which are having values based on that we can take further.
- Embarked: There are only two so we can drop or else we can go with mode.

=> We can observe from unique values of the feature columns
- Survived: 0 and 1 [Target Variable/Dependent Variable]
- Pclass: First Class, Second Class, third Class
- Sex: Male and Female
- Embarked: S, C, & Q

=> We can observe that there are no duplicate rows present in the data, we could have identified before cell of unique values as they are 891 rows and we got 891 unique rows.

```

#### ```4. Data Cleaning & Preparation```

- Handling Missing Values
- Removing Duplicates
- Type Casting columns
- Feature Engineering

In [ ]:
#

**5. Exploratory Data Analysis [EDA]**

**6. Visualization**

**7. Insights / Findings**

**8. Recommendations**

**9. Conclusion**

**----------------------------------------------------------------END----------------------------------------------------------------------------**